run:
  deadline: 2m
  skip-files:
    - ^unsecured
linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 12
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - gas
    - dupl
    - gomnd
    - wsl
    - nlreturn
    - prealloc
    - testpackage
    - paralleltest
    - tparallel
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustruct
    - noctx
    - makezero
    - forbidigo
    - varnamelen
    - contextcheck

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: version.go
      text: (version|date|commit) is a global variable
